# Generated by Django 5.1.5 on 2026-04-19 13:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('morning_litre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('evening_litre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cows/')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Age in years')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('number_of_pregnancy', models.PositiveIntegerField(blank=True, null=True)),
                ('average_litre_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('medicine', models.CharField(blank=True, max_length=255)),
                ('injection', models.CharField(blank=True, max_length=255)),
                ('is_bought', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('buyed_date', models.DateField(blank=True, null=True)),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dairy.cow')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', models.F('mother_id')), _negated=True), name='cow_not_own_mother')],
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('morning_litre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('evening_litre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('morning_status', models.CharField(choices=[('delivered', 'Delivered'), ('no_milk', 'No Milk')], default='delivered', max_length=20)),
                ('evening_status', models.CharField(choices=[('delivered', 'Delivered'), ('no_milk', 'No Milk')], default='delivered', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='dairy.customer')),
            ],
            options={
                'ordering': ['-date', 'customer__name'],
                'unique_together': {('customer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('total_litre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_bills', to='dairy.customer')),
            ],
            options={
                'ordering': ['-year', '-month', 'customer__name'],
                'unique_together': {('customer', 'month', 'year')},
            },
        ),
    ]
