# Generated by Django 6.0.4 on 2026-04-20 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0003_businesssetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSackPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('sack_count', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
    ]
