# Generated by Django 6.0.4 on 2026-04-21 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0004_feedsackpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CowDiseaseMonthlyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('is_given', models.BooleanField(default=False)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_statuses', to='dairy.cow')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cow_statuses', to='dairy.diseasetype')),
            ],
            options={
                'ordering': ['-year', '-month', 'disease__name'],
                'unique_together': {('cow', 'disease', 'month', 'year')},
            },
        ),
    ]
