# Generated by Django 6.0.4 on 2026-04-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0005_diseasetype_cowdiseasemonthlystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='currently_pregnant',
            field=models.BooleanField(default=False),
        ),
    ]
