# Generated by Django 6.0.4 on 2026-04-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0006_cow_currently_pregnant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('is_holiday', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
