# Generated by Django 6.0.4 on 2026-05-13 13:48

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0007_deliverydaystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='ear_tag_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='CowMarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('listed_on', models.DateField(default=datetime.date.today)),
                ('sold_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listing', to='dairy.cow')),
            ],
            options={
                'ordering': ['-listed_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CowTreatmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=120)),
                ('treatment', models.CharField(blank=True, max_length=180)),
                ('medicine_given', models.CharField(blank=True, max_length=180)),
                ('checkup_date', models.DateField(default=datetime.date.today)),
                ('worm_medicine', models.BooleanField(default=False)),
                ('monthly_checkup', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('treated_by', models.CharField(blank=True, max_length=120)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_logs', to='dairy.cow')),
            ],
            options={
                'ordering': ['-checkup_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CowMonthlyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('total_litre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('avg_litre_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_productions', to='dairy.cow')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('cow', 'month', 'year')},
            },
        ),
    ]
