# Generated by Django 6.0.4 on 2026-05-13 20:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0008_cow_ear_tag_number_cowmarketplacelisting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowMedicineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type', models.CharField(choices=[('deworming', 'Deworming'), ('fmd_vaccine', 'FMD Vaccine')], max_length=20)),
                ('given_on', models.DateField(default=datetime.date.today)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_records', to='dairy.cow')),
            ],
            options={
                'ordering': ['given_on', 'created_at'],
            },
        ),
    ]
