# Generated by Django 6.0.4 on 2026-06-18 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0009_cowmedicinerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssetting',
            name='data_reset_date',
            field=models.DateField(default=datetime.date(2026, 4, 1)),
        ),
    ]
